{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "926d3945-4124-4333-bc88-e09ba753abef",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Clean Streamlit app created as 'energy_app_clean.py'\n",
      "🚀 Run this command in terminal: streamlit run energy_app_clean.py\n"
     ]
    }
   ],
   "source": [
    "# Run this in a Jupyter cell to create a clean Streamlit app\n",
    "clean_code = '''import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import joblib\n",
    "from sklearn.metrics import mean_absolute_error, r2_score\n",
    "\n",
    "# Set page configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"Energy Consumption Predictor\",\n",
    "    page_icon=\"⚡\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# Custom CSS for better styling\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .main-header {\n",
    "        font-size: 2.5rem;\n",
    "        color: #1f77b4;\n",
    "        text-align: center;\n",
    "        margin-bottom: 1rem;\n",
    "    }\n",
    "    .prediction-box {\n",
    "        background-color: #f0f2f6;\n",
    "        padding: 25px;\n",
    "        border-radius: 10px;\n",
    "        border-left: 5px solid #1f77b4;\n",
    "        margin: 20px 0;\n",
    "    }\n",
    "    .feature-importance {\n",
    "        background-color: #e8f4fd;\n",
    "        padding: 15px;\n",
    "        border-radius: 8px;\n",
    "        margin: 10px 0;\n",
    "    }\n",
    "    .metric-box {\n",
    "        background-color: #ffffff;\n",
    "        padding: 15px;\n",
    "        border-radius: 8px;\n",
    "        border: 1px solid #e0e0e0;\n",
    "        margin: 5px 0;\n",
    "    }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "@st.cache_resource\n",
    "def load_model_and_components():\n",
    "    \"\"\"Load the pre-trained model and components\"\"\"\n",
    "    try:\n",
    "        model = joblib.load('best_energy_model.pkl')\n",
    "        scaler = joblib.load('feature_scaler.pkl')\n",
    "        feature_names = joblib.load('feature_names.pkl')\n",
    "        return model, scaler, feature_names\n",
    "    except FileNotFoundError as e:\n",
    "        st.error(f\"❌ Model files not found: {e}\")\n",
    "        st.info(\"Please make sure you've saved the model files in the same directory\")\n",
    "        return None, None, None\n",
    "\n",
    "def get_feature_ranges():\n",
    "    \"\"\"Define reasonable ranges for each feature based on your data\"\"\"\n",
    "    return {\n",
    "        'lights': (0, 100, 30),\n",
    "        'T1': (15, 30, 20),\n",
    "        'RH_1': (20, 80, 50),\n",
    "        'T2': (15, 30, 20),\n",
    "        'RH_2': (20, 80, 50),\n",
    "        'T3': (15, 30, 20),\n",
    "        'RH_3': (20, 80, 50),\n",
    "        'T4': (15, 30, 20),\n",
    "        'RH_4': (20, 80, 50),\n",
    "        'T5': (15, 30, 20),\n",
    "        'RH_5': (20, 80, 50),\n",
    "        'T6': (15, 30, 20),\n",
    "        'RH_6': (20, 80, 50),\n",
    "        'T7': (15, 30, 20),\n",
    "        'RH_7': (20, 80, 50),\n",
    "        'T8': (15, 30, 20),\n",
    "        'RH_8': (20, 80, 50),\n",
    "        'T9': (15, 30, 20),\n",
    "        'RH_9': (20, 80, 50),\n",
    "        'T_out': (-5, 35, 15),\n",
    "        'Press_mm_hg': (720, 780, 730),\n",
    "        'RH_out': (20, 100, 70),\n",
    "        'Windspeed': (0, 15, 5),\n",
    "        'Visibility': (0, 50, 25),\n",
    "        'Tdewpoint': (-5, 25, 10),\n",
    "        'rv1': (0, 50, 25),\n",
    "        'rv2': (0, 50, 25),\n",
    "        'hour': (0, 23, 12),\n",
    "        'day_of_week': (0, 6, 3),\n",
    "        'is_weekend': (0, 1, 0),\n",
    "        'temp_indoor_outdoor_diff': (-10, 10, 0),\n",
    "        'avg_indoor_temp': (15, 30, 22),\n",
    "        'avg_indoor_humidity': (20, 80, 50),\n",
    "        'lights_to_appliances_ratio': (0, 5, 1),\n",
    "        'is_working_hours': (0, 1, 1),\n",
    "        'is_sleeping_hours': (0, 1, 0)\n",
    "    }\n",
    "\n",
    "def main():\n",
    "    # Header\n",
    "    st.markdown('<h1 class=\"main-header\">⚡ Building Energy Consumption Predictor</h1>', unsafe_allow_html=True)\n",
    "    \n",
    "    # Load model\n",
    "    model, scaler, feature_names = load_model_and_components()\n",
    "    if model is None:\n",
    "        st.stop()\n",
    "    \n",
    "    # Sidebar navigation\n",
    "    st.sidebar.title(\"Navigation\")\n",
    "    app_mode = st.sidebar.selectbox(\n",
    "        \"Choose Section\",\n",
    "        [\"🏠 Home\", \"🔮 Make Prediction\", \"📊 Model Info\", \"🔍 Feature Analysis\"]\n",
    "    )\n",
    "    \n",
    "    # Home Page\n",
    "    if app_mode == \"🏠 Home\":\n",
    "        st.header(\"Welcome to the Energy Consumption Predictor!\")\n",
    "        \n",
    "        col1, col2 = st.columns([2, 1])\n",
    "        \n",
    "        with col1:\n",
    "            st.markdown(\"\"\"\n",
    "            ### About This App\n",
    "            This application predicts building energy consumption using a **Random Forest** machine learning model.\n",
    "            \n",
    "            **Model Performance:**\n",
    "            - 🎯 **R² Score: 0.7444** (74.44% variance explained)\n",
    "            - 📊 **MAE: 20.56 Wh** (Mean Absolute Error)\n",
    "            - 🤖 **Algorithm: Random Forest**\n",
    "            \n",
    "            **Key Features:**\n",
    "            - Real-time energy consumption predictions\n",
    "            - Interactive feature analysis\n",
    "            - Model performance insights\n",
    "            - User-friendly interface\n",
    "            \"\"\")\n",
    "        \n",
    "        with col2:\n",
    "            st.markdown(\"\"\"\n",
    "            <div style='background-color: #e8f4fd; padding: 20px; border-radius: 10px;'>\n",
    "            <h4>🚀 Quick Start</h4>\n",
    "            <ol>\n",
    "            <li>Go to <b>Make Prediction</b></li>\n",
    "            <li>Adjust feature values</li>\n",
    "            <li>Get instant energy prediction</li>\n",
    "            </ol>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "            \n",
    "            # Quick metrics\n",
    "            st.markdown(\"\"\"\n",
    "            <div class='metric-box'>\n",
    "            <h4>📈 Model Metrics</h4>\n",
    "            <p>R² Score: <b>0.7444</b></p>\n",
    "            <p>MAE: <b>20.56 Wh</b></p>\n",
    "            <p>Features: <b>36</b></p>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "    \n",
    "    # Prediction Page\n",
    "    elif app_mode == \"🔮 Make Prediction\":\n",
    "        st.header(\"🔮 Energy Consumption Prediction\")\n",
    "        \n",
    "        st.markdown(\"\"\"\n",
    "        <div class='prediction-box'>\n",
    "        <h3>Adjust the features below to predict energy consumption</h3>\n",
    "        <p>The model will predict energy usage based on your input values.</p>\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        # Get feature ranges\n",
    "        feature_ranges = get_feature_ranges()\n",
    "        \n",
    "        # Organize features by category\n",
    "        col1, col2, col3 = st.columns(3)\n",
    "        \n",
    "        input_features = {}\n",
    "        \n",
    "        with col1:\n",
    "            st.subheader(\"🏠 Indoor Environment\")\n",
    "            important_features = ['lights', 'T1', 'RH_1', 'T3', 'RH_3', 'T8']\n",
    "            for feature in important_features:\n",
    "                if feature in feature_ranges:\n",
    "                    min_val, max_val, default_val = feature_ranges[feature]\n",
    "                    input_features[feature] = st.slider(\n",
    "                        f\"{feature}\",\n",
    "                        min_val, max_val, default_val,\n",
    "                        help=f\"Adjust {feature} value\"\n",
    "                    )\n",
    "        \n",
    "        with col2:\n",
    "            st.subheader(\"🌤️ Outdoor & Weather\")\n",
    "            outdoor_features = ['T_out', 'RH_out', 'Press_mm_hg', 'Windspeed']\n",
    "            for feature in outdoor_features:\n",
    "                if feature in feature_ranges:\n",
    "                    min_val, max_val, default_val = feature_ranges[feature]\n",
    "                    input_features[feature] = st.slider(\n",
    "                        f\"{feature}\",\n",
    "                        min_val, max_val, default_val,\n",
    "                        help=f\"Adjust {feature} value\"\n",
    "                    )\n",
    "        \n",
    "        with col3:\n",
    "            st.subheader(\"⏰ Time & Engineered\")\n",
    "            time_features = ['hour', 'is_working_hours', 'is_sleeping_hours', 'lights_to_appliances_ratio']\n",
    "            for feature in time_features:\n",
    "                if feature in feature_ranges:\n",
    "                    min_val, max_val, default_val = feature_ranges[feature]\n",
    "                    \n",
    "                    if feature in ['is_working_hours', 'is_sleeping_hours']:\n",
    "                        input_features[feature] = st.selectbox(\n",
    "                            f\"{feature.replace('_', ' ').title()}\",\n",
    "                            [0, 1],\n",
    "                            index=default_val,\n",
    "                            format_func=lambda x: \"Yes\" if x == 1 else \"No\"\n",
    "                        )\n",
    "                    else:\n",
    "                        input_features[feature] = st.slider(\n",
    "                            f\"{feature.replace('_', ' ').title()}\",\n",
    "                            min_val, max_val, default_val,\n",
    "                            help=f\"Adjust {feature} value\"\n",
    "                        )\n",
    "        \n",
    "        # Fill remaining features with defaults\n",
    "        for feature in feature_names:\n",
    "            if feature not in input_features and feature in feature_ranges:\n",
    "                min_val, max_val, default_val = feature_ranges[feature]\n",
    "                input_features[feature] = default_val\n",
    "        \n",
    "        # Prediction button\n",
    "        if st.button(\"🚀 Predict Energy Consumption\", type=\"primary\", use_container_width=True):\n",
    "            try:\n",
    "                # Prepare input data\n",
    "                input_df = pd.DataFrame([input_features])[feature_names]\n",
    "                \n",
    "                # Make prediction\n",
    "                prediction = model.predict(input_df)[0]\n",
    "                \n",
    "                # Display result\n",
    "                st.markdown(f\"\"\"\n",
    "                <div style='background-color: #d4edda; padding: 30px; border-radius: 15px; border-left: 5px solid #28a745; text-align: center;'>\n",
    "                <h2 style='color: #155724; margin: 0;'>🎯 Prediction Result</h2>\n",
    "                <h1 style='color: #155724; margin: 20px 0;'>{prediction:.1f} Wh</h1>\n",
    "                <p style='color: #155724; font-size: 1.2rem; margin: 0;'>Estimated Energy Consumption</p>\n",
    "                </div>\n",
    "                \"\"\", unsafe_allow_html=True)\n",
    "                \n",
    "                # Interpretation\n",
    "                st.subheader(\"💡 Interpretation\")\n",
    "                if prediction < 30:\n",
    "                    st.success(\"**Very Low Consumption** - Minimal appliance usage\")\n",
    "                elif prediction < 60:\n",
    "                    st.info(\"**Low Consumption** - Typical for efficient usage\")\n",
    "                elif prediction < 120:\n",
    "                    st.warning(\"**Moderate Consumption** - Normal household activity\")\n",
    "                else:\n",
    "                    st.error(\"**High Consumption** - Heavy appliance usage\")\n",
    "                \n",
    "            except Exception as e:\n",
    "                st.error(f\"Prediction error: {e}\")\n",
    "    \n",
    "    # Model Info Page\n",
    "    elif app_mode == \"📊 Model Info\":\n",
    "        st.header(\"📊 Model Information\")\n",
    "        \n",
    "        col1, col2 = st.columns(2)\n",
    "        \n",
    "        with col1:\n",
    "            st.subheader(\"Model Performance\")\n",
    "            st.metric(\"R² Score\", \"0.7444\")\n",
    "            st.metric(\"Mean Absolute Error\", \"20.56 Wh\")\n",
    "            st.metric(\"Algorithm\", \"Random Forest\")\n",
    "            st.metric(\"Number of Features\", \"36\")\n",
    "        \n",
    "        with col2:\n",
    "            st.subheader(\"Model Details\")\n",
    "            st.markdown(\"\"\"\n",
    "            **Random Forest Regressor:**\n",
    "            - **n_estimators**: 100 trees\n",
    "            - **max_depth**: None (unlimited)\n",
    "            - **random_state**: 42\n",
    "            \n",
    "            **Training Data:**\n",
    "            - UCI Appliances Energy Dataset\n",
    "            - 19,735 total records\n",
    "            - 80/20 train/test split\n",
    "            \n",
    "            **Interpretation:**\n",
    "            - R² = 0.7444 means the model explains 74.44% of energy variance\n",
    "            - MAE = 20.56 Wh means average prediction error is about 20.56 Watt-hours\n",
    "            \"\"\")\n",
    "        \n",
    "        # Feature importance visualization\n",
    "        st.subheader(\"🔍 Feature Importance\")\n",
    "        if hasattr(model, 'feature_importances_'):\n",
    "            feature_importance = pd.DataFrame({\n",
    "                'feature': feature_names,\n",
    "                'importance': model.feature_importances_\n",
    "            }).sort_values('importance', ascending=False)\n",
    "            \n",
    "            fig, ax = plt.subplots(figsize=(10, 8))\n",
    "            top_15 = feature_importance.head(15)\n",
    "            \n",
    "            colors = plt.cm.viridis(np.linspace(0, 1, len(top_15)))\n",
    "            bars = ax.barh(top_15['feature'], top_15['importance'], color=colors)\n",
    "            ax.set_xlabel('Feature Importance')\n",
    "            ax.set_title('Top 15 Most Important Features', fontweight='bold')\n",
    "            ax.grid(True, alpha=0.3)\n",
    "            plt.gca().invert_yaxis()\n",
    "            \n",
    "            st.pyplot(fig)\n",
    "    \n",
    "    # Feature Analysis Page\n",
    "    elif app_mode == \"🔍 Feature Analysis\":\n",
    "        st.header(\"🔍 Feature Analysis\")\n",
    "        \n",
    "        st.subheader(\"Top 10 Most Important Features\")\n",
    "        if hasattr(model, 'feature_importances_'):\n",
    "            feature_importance = pd.DataFrame({\n",
    "                'feature': feature_names,\n",
    "                'importance': model.feature_importances_\n",
    "            }).sort_values('importance', ascending=False)\n",
    "            \n",
    "            # Display top 10 features\n",
    "            top_10 = feature_importance.head(10)\n",
    "            \n",
    "            for i, (idx, row) in enumerate(top_10.iterrows(), 1):\n",
    "                importance_pct = (row['importance'] / feature_importance['importance'].sum()) * 100\n",
    "                \n",
    "                st.markdown(f\"\"\"\n",
    "                <div class='feature-importance'>\n",
    "                <h4>#{i}: {row['feature']}</h4>\n",
    "                <p>Importance: <b>{row['importance']:.4f}</b> ({importance_pct:.1f}% of total)</p>\n",
    "                </div>\n",
    "                \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "'''\n",
    "\n",
    "# Save the clean code to a new file\n",
    "with open('energy_app_clean.py', 'w') as f:\n",
    "    f.write(clean_code)\n",
    "\n",
    "print(\"✅ Clean Streamlit app created as 'energy_app_clean.py'\")\n",
    "print(\"🚀 Run this command in terminal: streamlit run energy_app_clean.py\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "466c7136-c69d-46c1-aa2d-82106732bb11",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
